const fs = require('fs');

const path = 'src/data/initialData.ts';
let content = fs.readFileSync(path, 'utf8');

const newDevDesignTools = `
  {
    id: 'res-tool-json-yaml',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.98,
    reviewCount: 110,
    viewsCount: 14500,
    downloadsCount: 5200,
    faqs: [
      { question: 'Is my JSON data uploaded to any external server?', answer: 'No. All conversion between JSON, YAML, and CSV runs 100% locally in your client browser.' }
    ],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free JSON to YAML & CSV Online Converter',
    slug: 'json-yaml-csv-converter-tool',
    metaDescription: 'Instantly convert JSON data into clean YAML and CSV tables in your browser. Fast, free, and privacy-focused.',
    type: 'calculator',
    category: 'calculators',
    tags: ['JSON', 'YAML', 'CSV', 'Developer Tools', 'Data Converter'],
    featuredImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Convert JSON objects and arrays into formatted YAML or CSV spreadsheets instantly.',
    interactiveConfig: { toolType: 'json-yaml-converter' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Browser-Based Data Conversion' }]
  },

  {
    id: 'res-tool-sql-beautifier',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.96,
    reviewCount: 94,
    viewsCount: 12100,
    downloadsCount: 4300,
    faqs: [
      { question: 'Which SQL dialects are supported?', answer: 'Supports standard ANSI SQL, PostgreSQL, MySQL, SQLite, and MS SQL query syntax formatting.' }
    ],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free SQL Query Beautifier & Formatter',
    slug: 'sql-query-beautifier-formatter',
    metaDescription: 'Format messy SQL queries into readable, capitalized, and indented code blocks instantly.',
    type: 'calculator',
    category: 'calculators',
    tags: ['SQL', 'Database', 'Formatter', 'Developer Tools', 'PostgreSQL'],
    featuredImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Format, capitalize keywords, and clean up complex SQL queries in one click.',
    interactiveConfig: { toolType: 'sql-formatter-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'SQL Query Formatting Made Simple' }]
  },

  {
    id: 'res-tool-cron-parser',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: false,
    isPremium: false,
    rating: 4.93,
    reviewCount: 82,
    viewsCount: 9800,
    downloadsCount: 3100,
    faqs: [
      { question: 'How do standard 5-field cron expressions work?', answer: 'Cron fields represent minute, hour, day of month, month, and day of week.' }
    ],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free Cron Expression Parser & Generator',
    slug: 'cron-expression-parser-tool',
    metaDescription: 'Parse crontab expressions into plain human-readable descriptions instantly.',
    type: 'calculator',
    category: 'calculators',
    tags: ['Cron', 'DevOps', 'Scheduler', 'Linux', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Translate complex cron expressions into human-readable schedule explanations.',
    interactiveConfig: { toolType: 'cron-parser-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Cron Schedule Translation' }]
  },

  {
    id: 'res-tool-unix-timestamp',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: false,
    isPremium: false,
    rating: 4.94,
    reviewCount: 76,
    viewsCount: 8900,
    downloadsCount: 2900,
    faqs: [],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free Unix Epoch Timestamp Converter',
    slug: 'unix-timestamp-converter-tool',
    metaDescription: 'Convert Unix timestamps in seconds/milliseconds to human readable UTC and local dates.',
    type: 'calculator',
    category: 'calculators',
    tags: ['Unix Timestamp', 'Epoch', 'Date Converter', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Convert Epoch timestamps to human readable dates in UTC and local timezone.',
    interactiveConfig: { toolType: 'unix-timestamp-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Unix Timestamp Converter' }]
  },

  {
    id: 'res-tool-jwt-decoder',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.97,
    reviewCount: 125,
    viewsCount: 16200,
    downloadsCount: 5800,
    faqs: [
      { question: 'Is my secret JWT token sent over the internet?', answer: 'No. Tokens are decoded locally in your browser using standard base64 parsing.' }
    ],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free Online JWT Decoder & Inspector',
    slug: 'jwt-decoder-token-inspector',
    metaDescription: 'Decode JSON Web Tokens (JWT) to inspect header details, claims, subject, and expiration date.',
    type: 'calculator',
    category: 'calculators',
    tags: ['JWT', 'Authentication', 'Security', 'OAuth', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Decode JWT tokens instantly to view claims, header parameters, and expiration status.',
    interactiveConfig: { toolType: 'jwt-decoder-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'JWT Token Decoding' }]
  },

  {
    id: 'res-tool-base64-uuid',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.99,
    reviewCount: 140,
    viewsCount: 18900,
    downloadsCount: 7100,
    faqs: [],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Base64 Encoder, UUID v4 & Password Generator',
    slug: 'base64-uuid-password-generator-tool',
    metaDescription: 'Encode/decode Base64 text, generate cryptographic UUID v4 tokens, and build strong random passwords.',
    type: 'calculator',
    category: 'calculators',
    tags: ['Base64', 'UUID', 'Password Generator', 'Security', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Encode Base64, generate cryptographically secure UUID v4 tokens and passwords.',
    interactiveConfig: { toolType: 'base64-hash-uuid-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Base64 & Security Generator Suite' }]
  },

  {
    id: 'res-tool-regex-tester',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.98,
    reviewCount: 118,
    viewsCount: 15400,
    downloadsCount: 5600,
    faqs: [],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free Regular Expression (RegEx) Tester',
    slug: 'regex-tester-pattern-matcher',
    metaDescription: 'Test regular expressions against target text strings in real-time with instant match highlighting.',
    type: 'calculator',
    category: 'calculators',
    tags: ['RegEx', 'Pattern Matching', 'JavaScript', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Test RegEx patterns with flag support and real-time substring match highlighting.',
    interactiveConfig: { toolType: 'regex-tester-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'RegEx Testing & Pattern Validation' }]
  },

  {
    id: 'res-tool-diff-checker',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub DevTools' }],
    isFeatured: false,
    isPremium: false,
    rating: 4.95,
    reviewCount: 88,
    viewsCount: 10400,
    downloadsCount: 3800,
    faqs: [],
    createdBy: 'admin-devtools',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free Side-by-Side Text & Code Diff Checker',
    slug: 'side-by-side-text-diff-checker',
    metaDescription: 'Compare two blocks of code or text side-by-side to highlight additions, deletions, and modifications.',
    type: 'calculator',
    category: 'calculators',
    tags: ['Diff Checker', 'Code Comparison', 'Git', 'Developer Tools'],
    featuredImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Side-by-side text and code comparison to spot changes and version differences.',
    interactiveConfig: { toolType: 'diff-checker-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Code & Text Diff Comparison' }]
  },

  {
    id: 'res-tool-wcag-contrast',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub Design' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.99,
    reviewCount: 132,
    viewsCount: 17800,
    downloadsCount: 6400,
    faqs: [
      { question: 'What contrast ratio is required for WCAG AA compliance?', answer: 'A minimum contrast ratio of 4.5:1 is required for standard text, and 3:1 for large text (18pt+ or 14pt bold).' }
    ],
    createdBy: 'admin-design',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'WCAG Color Contrast Calculator & Color Converter',
    slug: 'wcag-color-contrast-calculator',
    metaDescription: 'Calculate WCAG AA and AAA color contrast ratios, convert Hex to RGB/HSL, and check UI accessibility.',
    type: 'calculator',
    category: 'calculators',
    tags: ['WCAG', 'Accessibility', 'Color Contrast', 'UI Design', 'Hex RGB HSL'],
    featuredImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Verify WCAG 2.1 AA/AAA color contrast ratios and convert Hex, RGB, and HSL color values.',
    interactiveConfig: { toolType: 'wcag-color-contrast-tool' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Color Contrast & Accessibility Verification' }]
  },

  {
    id: 'res-tool-opengraph-card',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub Design' }],
    isFeatured: true,
    isPremium: false,
    rating: 4.96,
    reviewCount: 95,
    viewsCount: 11900,
    downloadsCount: 4100,
    faqs: [],
    createdBy: 'admin-design',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'Free OpenGraph Social Media Preview Card Generator',
    slug: 'opengraph-social-card-generator',
    metaDescription: 'Design and preview custom 1200x630 OpenGraph social media sharing cards for Twitter, LinkedIn, and Facebook.',
    type: 'calculator',
    category: 'calculators',
    tags: ['OpenGraph', 'Social Media', 'SEO', 'Design Tools', 'Twitter Cards'],
    featuredImage: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Generate beautiful 1200x630 OpenGraph social media preview cards for blog posts.',
    interactiveConfig: { toolType: 'opengraph-card-generator' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'OpenGraph Card Creation' }]
  },

  {
    id: 'res-tool-image-compressor',
    status: 'published',
    versionHistory: [{ version: 'v1.0.0', date: '2026-08-04', changes: 'Initial release', author: 'ResourceHub Design' }],
    isFeatured: false,
    isPremium: false,
    rating: 4.94,
    reviewCount: 81,
    viewsCount: 9500,
    downloadsCount: 3400,
    faqs: [],
    createdBy: 'admin-design',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: 'In-Browser Image Converter & WebP Compressor',
    slug: 'in-browser-image-converter-compressor',
    metaDescription: 'Convert PNG and JPEG images to WebP format with quality sliders and file size savings estimation.',
    type: 'calculator',
    category: 'calculators',
    tags: ['WebP', 'Image Compressor', 'Image Converter', 'Core Web Vitals'],
    featuredImage: 'https://images.unsplash.com/photo-1542744094-3a3172720449?auto=format&fit=crop&w=1200&q=80',
    shortSummary: 'Compress image files and convert formats to next-gen WebP to boost Core Web Vitals.',
    interactiveConfig: { toolType: 'image-compressor-converter' },
    contentBlocks: [{ id: 'b1', type: 'heading', content: 'Web Image Optimization' }]
  },
`;

content = content.replace('export const INITIAL_RESOURCES: Resource[] = [', 'export const INITIAL_RESOURCES: Resource[] = [' + newDevDesignTools);

fs.writeFileSync(path, content, 'utf8');
console.log('Successfully inserted all developer & design utility tools into initialData.ts');
